=== DiegoLangreo7/IIS-SEW/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" 
           elementFormDefault="qualified" 
           targetNamespace="http://www.uniovi.es" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema">    
    <xs:element name="circuitos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="circuito" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="circuito">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nombre" />
                <xs:element ref="longitudC" />
                <xs:element ref="anchuraC" />
                <xs:element ref="fecha" />
                <xs:element ref="hora" />
                <xs:element ref="nvueltas" />
                <xs:element ref="localidad" />
                <xs:element ref="pais" />
                <xs:element minOccurs="3" maxOccurs="unbounded" ref="referencias" />
                <xs:element minOccurs="1" maxOccurs="5" ref="fotografias" />
                <xs:element minOccurs="0" maxOccurs="3" ref="videos" />
                <xs:element ref="coordenadas" />
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="tramos" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nombre" type="xs:string" />
    <xs:element name="longitudC">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="longitud" />
                <xs:element ref="unidad" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="longitud" type="longitudType" />
    <xs:element name="unidad" type="xs:string" />
    <xs:element name="anchuraC">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="anchura" />
                <xs:element ref="unidad" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="anchura" type="xs:float" />
    <xs:element name="fecha" type="xs:date" />
    <xs:element name="hora" type="xs:time" />
    <xs:element name="nvueltas" type="xs:integer" />
    <xs:element name="localidad" type="xs:string" />
    <xs:element name="pais" type="xs:string" />
    <xs:element name="referencias" type="xs:string" />
    <xs:element name="fotografias" type="xs:string" />
    <xs:element name="videos" type="xs:string" />
    <xs:element name="tramos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="distanciaT" />
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="coordenadas" />
                <xs:element ref="sector" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="distanciaT">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="distancia" />
                <xs:element ref="unidad" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="distancia" type="xs:float" />
    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="longitud" />
                <xs:element ref="latitud" />
                <xs:element ref="altitud" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="latitud" type="latitudType" />
    <xs:element name="altitud" type="altitudType" />
    <xs:element name="sector" type="xs:integer" />

    <xs:simpleType name="latitudType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-90" />
            <xs:maxInclusive value="90" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="longitudType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="-180" />
            <xs:maxInclusive value="180" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="altitudType">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="5000" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== DiegoLangreo7/IIS-SEW/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuitos xmlns="http://www.uniovi.es" 
           xmlns:uni="http://www.uniovi.es" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
	<uni:circuito>
		<uni:nombre>Autodromo Nazionale Monza</uni:nombre>
		<uni:longitudC>
			<uni:longitud>5.793</uni:longitud>
			<uni:unidad>kil√≥metros</uni:unidad>
		</uni:longitudC>
		<uni:anchuraC>
			<uni:anchura>12</uni:anchura>
			<uni:unidad>metros</uni:unidad>
		</uni:anchuraC>
		<uni:fecha>2023-09-01</uni:fecha>
		<uni:hora>15:00:00</uni:hora>
		<uni:nvueltas>53</uni:nvueltas>
		<uni:localidad>Monza</uni:localidad>
		<uni:pais>Italia</uni:pais>
		<uni:referencias>https://www.formula1.com/en/racing/2024/italy/circuit</uni:referencias>
		<uni:referencias>https://es.wikipedia.org/wiki/Autodromo_Nazionale_di_Monza</uni:referencias>
		<uni:referencias>https://www.dazn.com/es-ES/news/motor/circuito-monza-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-italia-mundial-f1/1rvwgg1hco88f14fi4ivfb1g00</uni:referencias>
		<uni:fotografias>CircuitoMonza.jpg</uni:fotografias>
		<uni:fotografias>CircuitoMonzaEsquema.jpg</uni:fotografias>
		<uni:coordenadas>
			<uni:longitud>9.281197983803695</uni:longitud>
			<uni:latitud>45.61897580466426</uni:latitud>
			<uni:altitud>184</uni:altitud>
		</uni:coordenadas>

		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>400</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.281153446860143</uni:longitud>
				<uni:latitud>45.61902167151543</uni:latitud>
				<uni:altitud>184</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.281956712842607</uni:longitud>
				<uni:latitud>45.624557165951565</uni:latitud>
				<uni:altitud>187</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>47</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.281956712842607</uni:longitud>
				<uni:latitud>45.624557165951565</uni:latitud>
				<uni:altitud>187</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.2823079707826</uni:longitud>
				<uni:latitud>45.62455255999843</uni:latitud>
				<uni:altitud>187</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>160</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.2823079707826</uni:longitud>
				<uni:latitud>45.62455255999843</uni:latitud>
				<uni:altitud>187</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.282471285692782</uni:longitud>
				<uni:latitud>45.624697569342224</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>160</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.282471285692782</uni:longitud>
				<uni:latitud>45.624697569342224</uni:latitud>
				<uni:altitud>187</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.282073215701873</uni:longitud>
				<uni:latitud>45.626041180338014</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>230</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.282073215701873</uni:longitud>
				<uni:latitud>45.626041180338014</uni:latitud>
				<uni:altitud>189</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.282341150661512</uni:longitud>
				<uni:latitud>45.62795507241801</uni:latitud>
				<uni:altitud>190</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>230</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.282341150661512</uni:longitud>
				<uni:latitud>45.62795507241801</uni:latitud>
				<uni:altitud>189</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.28490859348449</uni:longitud>
				<uni:latitud>45.62970872439507</uni:latitud>
				<uni:altitud>190</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>450</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.28490859348449</uni:longitud>
				<uni:latitud>45.62970872439507</uni:latitud>
				<uni:altitud>190</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.290829308791777</uni:longitud>
				<uni:latitud>45.63017071670176</uni:latitud>
				<uni:altitud>192</uni:altitud>
			</uni:coordenadas>
			<uni:sector>1</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>51</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.290824848266983</uni:longitud>
				<uni:latitud>45.630171722076014</uni:latitud>
				<uni:altitud>192</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.2914928798814</uni:longitud>
				<uni:latitud>45.6302377128988</uni:latitud>
				<uni:altitud>192</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>35</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.2914928798814</uni:longitud>
				<uni:latitud>45.6302377128988</uni:latitud>
				<uni:altitud>192</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.291636916448745</uni:longitud>
				<uni:latitud>45.63058329515153</uni:latitud>
				<uni:altitud>192</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>350</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.291635914553758</uni:longitud>
				<uni:latitud>45.63058115839124</uni:latitud>
				<uni:altitud>192</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.29563225390448</uni:longitud>
				<uni:latitud>45.63138147322369</uni:latitud>
				<uni:altitud>190</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>89</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.295647254411888</uni:longitud>
				<uni:latitud>45.63138368540972</uni:latitud>
				<uni:altitud>190</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.296544502054092</uni:longitud>
				<uni:latitud>45.6309282466757</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>270</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.296544502054092</uni:longitud>
				<uni:latitud>45.6309282466757</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.296830666715861</uni:longitud>
				<uni:latitud>45.62845062726081</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>270</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.296830666715861</uni:longitud>
				<uni:latitud>45.62845062726081</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.29195015176665</uni:longitud>
				<uni:latitud>45.62647393086959</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>1181</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.29195015176665</uni:longitud>
				<uni:latitud>45.62647393086959</uni:latitud>
				<uni:altitud>188</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.285975342749621</uni:longitud>
				<uni:latitud>45.62281028150105</uni:latitud>
				<uni:altitud>186</uni:altitud>
			</uni:coordenadas>
			<uni:sector>2</uni:sector>
		</uni:tramos>

		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>110</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.285988005287624</uni:longitud>
				<uni:latitud>45.62282043031515</uni:latitud>
				<uni:altitud>186</uni:altitud>
			</uni:coordenadas>
			<uni:coordenadas>
				<uni:longitud>9.285838313943566</uni:longitud>
				<uni:latitud>45.62180961215636</uni:latitud>
				<uni:altitud>186</uni:altitud>
			</uni:coordenadas>
			<uni:sector>3</uni:sector>
		</uni:tramos>
		
		<uni:tramos>
			<uni:distanciaT>
				<uni:distancia>100</uni:distancia>
				<uni:unidad>metros</uni:unidad>
			</uni:distanciaT>
			<uni:coordenadas>
				<uni:longitud>9.285838313943566</uni:longitud>
				<uni:latitud>45.62180961215636</uni:latitud>
